### ISSUE TITLE
Deep links aren't resolving

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/cityatlas#7]
If you go to a deep link in CityAtlas like:

https://cityatlas.phila.gov/#/1234%20MARKET%20ST/property

it times out. The bare `cityatlas.phila.gov` URL is fine. Probably a problem with CloudFront.

/cc @ajrothwell @jamesmbentley

**Comment by jamesmbentley** [comment]
@rbrtmrtn I don't think CityAtlas uses CloudFront. There is no HTTPS for cityatlas.phila.gov

/cc @ajrothwell

**Comment by rbrtmrtn** [comment]
Oh right, that’s just Atlas. We might have to open a ticket with Networking
then?

**Comment by jamesmbentley** [comment]
CityAtlas is still hosted in S3, it just wasn't set up to use HTTPS and CloudFront. @ajrothwell may remember why the decision was made.

**Comment by rbrtmrtn** [comment]
I think it was because we couldn’t do IP limiting with CloudFront -
something like that.

**Comment by jamesmbentley** [comment]
That was it, we would need to set up  Private Content - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html
